<?php
class Juego extends Soporte
{
    public  string $consola;
    private int $minNumJugadores;
    private int $maxNumJugadores;

    public function __construct(string $titulo, int $numero, float $precio, string $consola, int $minNumJugadores, int $maxNumJugadores)
    {
        parent::__construct($titulo, $numero, $precio);
        $this->consola=$consola;
        $this->minNumJugadores=$minNumJugadores;
        $this->maxNumJugadores=$maxNumJugadores;
    }


    public function muestraResumen()
    {
        if ($this->maxNumJugadores == $this->minNumJugadores) {
            echo parent::muestraResumen() . "<br>Consola: " . $this->consola . "<br> Para un jugador"; // TODO: Change the autogenerated stub

        }
        else    echo parent::muestraResumen() . "<br>Consola: " . $this->consola . "<br> De " . $this->minNumJugadores .
            " a " . $this->maxNumJugadores." jugadores"; // TODO: Change the autogenerated stub

    }
}