<?php
namespace app;
class CintaVideo extends Soporte
{
private string $duracion;

    public function __construct(string $titulo, int $numero, float $precio, string $duracion)
    {
        parent::__construct($titulo, $numero, $precio);
        $this->duracion=$duracion;
    }


    public function muestraResumen()
    {
        echo parent::muestraResumen()."<br>Duración: ".$this->duracion." minutos"; // TODO: Change the autogenerated stub
    }


}