<?php
namespace ProyectoVideoclub;
class Dvd extends Soporte
{
    public string $idioma;
    private string $formatPantalla;

    public function __construct(string $titulo, int $numero, float $precio, string $idioma, string $formatPantalla)
    {
        parent::__construct($titulo, $numero, $precio);
        $this->formatPantalla=$formatPantalla;
        $this->idioma=$idioma;
    }


    public function muestraResumen()
    {
        echo parent::muestraResumen()."<br>Idioma: ".$this->idioma."<br>Relación de aspecto: ".$this->formatPantalla; // TODO: Change the autogenerated stub
    }


}